services:
  web:
    build:
      context: ../
      dockerfile: docker/web/dockerfile
    networks:
      netlink: {}
      dblink: {}
    ports:
      - "7708:443"
    volumes:
      - ../web:/srv/web

  db:
    build:
      context: ../
      dockerfile: docker/db/dockerfile
    networks:
      dblink: {}

networks:
  netlink:
  dblink:
    driver: bridge
