name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: eu-north-1
  ECR_URL: 139073842005.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPO: tomada16/bsiaw

jobs:
  build-and-push:
    name: Build + Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy SAST scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'
          ignore-unfixed: false

      - name: Build & tag the docker image
        id: step-build
        run: |
          docker build -t tomada16/bsiaw .
          docker tag "tomada16/bsiaw:latest" "${{ env.ECR_URL }}/${{ env.ECR_REPO }}:latest"

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ env.ECR_URL }}/${{ env.ECR_REPO }}:latest'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '1'
          ignore-unfixed: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Check cosign installation
        run: cosign version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push to ECR
        run: |
          docker push "${{ env.ECR_URL }}/${{ env.ECR_REPO }}:latest"

      - name: Sign docker image
        env:
          COSIGN_PASSWORD: ""
        run: |
          echo "${{ secrets.BSIAW_SIGNING_KEY }}" | base64 -d > /tmp/bsiaw.key
          cosign sign --key /tmp/bsiaw.key "${{ env.ECR_URL }}/${{ env.ECR_REPO }}:latest"
          rm -f /tmp/bsiaw.key

      - name: Redeploy ECS containers testing testing
        run: |
          aws ecs update-service --cluster bsiaw --service bsiaw-webserver-service-fldtkco7 \
            --force-new-deployment
